### ISSUE TITLE
Replace custom config loading with Boto's own loading of `~/.aws/credentials`

### ISSUE THREAD

**Issue by ashb** [ministryofjustice/bootstrap-cfn#1]
Boto has built in [config loading](http://boto.readthedocs.org/en/latest/boto_config_tut.html) for credentials already and support for multiple accounts – we should work out how to use this

An example of how this works:

``` ipython
In [10]: c = connect_to_region("eu-west-1", profile_name="intra")

In [11]: c.get_all_instances()
Out[11]:
[Reservation:r-a77edfe7,
 Reservation:r-c4650a86,
 Reservation:r-0925624b,
 Reservation:r-0a4347ef,
…
 Reservation:r-ba5770f8,
 Reservation:r-f82b89b8,
 Reservation:r-c10f6683,
 Reservation:r-b092f4f2]
```

My `~/.aws/credentials` has this in it:

``` ini
[intra]
aws_access_key_id = AKIA**xxx**
aws_secret_access_key = xxx
```

(As a bonus it means we don't need the super generic `~/.config.yaml` file)

**Comment by stuartornum** [comment]
Happy to use this!

**Comment by ashb** [comment]
In trello https://trello.com/c/zbAlzdaU
