### ISSUE TITLE
Let Cloudformation generate names for S3 resources

### ISSUE THREAD

**Issue by ashb** [ministryofjustice/bootstrap-cfn#123]
We currently hard code the name of the ELB, RDS and S3 buckets that bootstrap-cfn creates.

This means that creating duplicate environments of the same flavour (i.e. another 'dev' env) means we have to duplicate the block in the YAML and change some identifiers.

Instead we can do this:

``` json
{
    "Outputs": {
      "staticbucket": {
        "Description": "x",
        "Value": { "Ref": "StaticBucket" }
      }
    },
    "Resources": {
        "StaticBucket": {
            "Properties": {
                "AccessControl": "BucketOwnerFullControl"
            },
            "Type": "AWS::S3::Bucket"
        }
    }
}
```

Note how there's no `BucketName` specified.

I went and created this template and cloudformation with a stack name of "Ash-s3-test" and the bucket that was created was `ash-s3-test-staticbucket-1hgn7cc7bhnak` – that's `<stackname>-<logical-resource-name>-<random>`. Given that we can make it an output this means we can find the name given in the same way we do with RDS.

We should do similar things for the ELB (where the name of ELB doesn't matter, just the DNS name) and RDS (which we don't need the name at all anyway - just the endpoint which is already an output)

**Comment by sevenmachines** [comment]
https://github.com/ministryofjustice/bootstrap-cfn/pull/132
Creates the bootstrap functions and changes needed to allow random naming of buckets

https://github.com/ministryofjustice/template-deploy/pull/114
Changes template deploy to use the new system

**Comment by sevenmachines** [comment]
If we can seperate out doing something similar for RDS and ELB's into other issues, to keep the PR size reviewable
