### ISSUE TITLE
get_stack_name uses fallback name when route53 lookup fails

### ISSUE THREAD

**Issue by sevenmachines** [ministryofjustice/bootstrap-cfn#170]
get_stack_name uses fallback name of <application>_<environment> when route53 lookup fails. This was done for backwards compatibility reasons. Unfortunately this has the side effect of masking any route53 stack_name lookup error, which all new stacks should have. This seems more damaging and time-consuming than defaulting to failure.

**Comment by mattpep** [comment]
What about having the failure be default (as you so describe) but also adding an option such as `use_legacy_stack_names` which defaults to false but can be set to true. That way both modes of behaviour can be achieved with the proposed one being default. (I'm struggling to contrive a scenario where we might want that, but perhaps someone else can think of one)

**Comment by sevenmachines** [comment]
its an option, one way would be to allow environment variables like
BOOTSTRAP_CFN_STACK_NAME_FALLBACK=True
something like that
