### ISSUE TITLE
ELB resource should have options for SSL certs and communication protocol

### ISSUE THREAD

**Issue by milosgajdos** [ministryofjustice/bootstrap-cfn#4]
At the moment by default `bootstrap-cfn` creates TCP based ELBs. 

There should be an option of a communication protocol. In practice we mostly use HTTP/HTTPs Load Balancers, anyways.

On top of this, you should have an option to specify a path to SSL certificates and keys if you need to create TCP(SSL)/HTTPS ELB.

**Comment by stuartornum** [comment]
Personally - I don't think we should put SSL certs on the ELB as it makes the process of updating the certs harder (it's easier to manage via salt) - also as we will be running nginx on each docker host, it's not extra overhead to run SSL there as well

**Comment by milosgajdos** [comment]
Right. This is a valid point. I'm closing this issue.
