### ISSUE TITLE
EC2 instance SG not included in RDS instance's SG

### ISSUE THREAD

**Issue by milosgajdos** [ministryofjustice/bootstrap-cfn#5]
When creating CF stack which has EC2 instance(s) and RDS, RDS SG does not include EC2's SG.
This has a consequence of EC2 instance not being able to communicate with RDS instance.

This is a similar issue to https://github.com/ministryofjustice/bootstrap-cfn/issues/13

**Comment by ashb** [comment]
@mattmb Was this also fixed in #51 – i.e. can we now specify a SG of the EC2 instances by reference to allow from the RDS?

**Comment by mattmb** [comment]
Don't think it is because I don't think we've added a way to specify the SGs in the RDS section of the yaml.
