### ISSUE TITLE
Config option to control VPC IP ranges

### ISSUE THREAD

**Issue by mattmb** [ministryofjustice/bootstrap-cfn#58]
https://github.com/ministryofjustice/bootstrap-cfn/blob/master/bootstrap_cfn/stacks/base.json#L11-L14
I'd like to make the above optionally set in the config file so that we can create VPCs which don't overlap.

Otherwise you can't peer the VPCs.

**Comment by pidah** [comment]
we need to discuss this asap

**Comment by stuartornum** [comment]
This should be easy enough to put into the YAML file

**Comment by stuartornum** [comment]
Merged: https://github.com/ministryofjustice/bootstrap-cfn/pull/73
