### ISSUE TITLE
Bootstrap automatically on instance create

### ISSUE THREAD

**Issue by mattmb** [ministryofjustice/bootstrap-cfn#60]
Investigate bootstrapping salt in an ASG.

At the moment we run the bootstrap from fabric. This has the disadvantage that auto scaling is not auto!

Things to think about:
- picking a master
- exchanging keys

**Comment by ashb** [comment]
There can be two different types of auto. The initial bootstrap when building a new stack could be done (partly) via fabric, but growing an Auto Scaling Group could be automatic.

**Comment by koikonom** [comment]
Given that all scripts run bootstrap-salt.sh, we could change the script in a way that if a SaltMaster tag was found then salt install would happen in that script instead of having fabric do it as an extra step.

The challenge is salt key management, we'd probably have to do something "magic" with pre-generated salt keys...

**Comment by mattmb** [comment]
Yeah i started investigating with S3 and IAM roles. It seemed promising. Something like, poke the master to create a key. Master uploads to private bucket. Minion downloads from bucket (it has permission from IAM role).

**Comment by koikonom** [comment]
Take a look at this http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-hup.html. These tools get installed during instance creation (again, see bootstrap-salt.sh).

We could use that on the master to trigger the key creation...

**Comment by ashb** [comment]
See also https://medium.com/teamrock-devtech/continuous-delivery-in-an-autoscaling-environment-97e77c4e624e

**Comment by mattmb** [comment]
Moved to https://github.com/ministryofjustice/bootstrap-salt/issues/15
