### ISSUE TITLE
Delete bucket contents before stack.

### ISSUE THREAD

**Issue by mattmb** [ministryofjustice/bootstrap-cfn#78]
Stack deletion will fail if there is content in the S3 bucket.

If the S3 bucket is just for static assets then we should delete the contents of the bucket before we delete the stack.

**Comment by ashb** [comment]
We need to be very careful about this. Sometimes it is that, but sometimes it's not.

**Comment by stuartornum** [comment]
Don't delete anything from S3 - gonna hurt us later if we do...

**Comment by mattmb** [comment]
We already delete the RDS instance as part of the stack delete. Surely that's even more dangerous. Is there anyway we could make it so that RDS/S3 get a unique ID and aren't deleted with the rest of the stack?

**Comment by ashb** [comment]
No don't think so - If that's what we want we'd have to just create those resources separately. With the RDS that's basically impossible as it's in the VPC. Referring to an S3 bucket that is created/managed separately is possible without too much hassle I think.

**Comment by ashb** [comment]
Closing this for now. No one is calling out for this at the moment. If anyone wants this feel free to re-open
