### ISSUE TITLE
Support RDS encryption

### ISSUE THREAD

**Issue by mattmb** [ministryofjustice/bootstrap-cfn#80]
https://github.com/ministryofjustice/bootstrap-cfn/blob/master/bootstrap_cfn/config.py#L127

At the moment we can't enable RDS encryption (StorageEncrypted) because it's not in the required fields list (see above).

Either we need to PR it in and then add it to **all** the yaml files. Or we need to support merging in non-required fields.

**Comment by stuartornum** [comment]
Add it to required fields I think - makes the options clearer

**Comment by mattmb** [comment]
And then every project has to update their yaml file?
