### ISSUE TITLE
Imports in error utils when using salt_utills on master

### ISSUE THREAD

**Issue by mattmb** [ministryofjustice/bootstrap-cfn#82]
We call the salt_utils script without installing fabric and dependencies on the salt-master.

Because it imports some functions from utils.py it blows up here:
https://github.com/ministryofjustice/bootstrap-cfn/blob/master/bootstrap_cfn/utils.py#L9

Either we'll have to bite the bullet and install all the python requirements during the bootstrap process or we'll have to move this import into the function that uses it.

**Comment by ashb** [comment]
Two things we could do:
1. import these only where they are used (i.e. in the tail function which won't be called on the host)
2. We separate out the stuff that is meant to be used on a host to a different file (or hell a different module >_>)

**Comment by ciprianc** [comment]
Solved by https://github.com/ministryofjustice/bootstrap-cfn/commit/a9af4fd3c67460b4fa9709c9892d70e35f766af7 in the trim-fat branch. Once that's merged into master this issue can be closed.

**Comment by mattmb** [comment]
Thanks @ciprianc :+1:
