### ISSUE TITLE
RDS `storage-type` ignored due to using `DBSecurityGroups`

### ISSUE THREAD

**Issue by stuartornum** [ministryofjustice/bootstrap-cfn#88]
This makes total sense AWS ?!?! (Not)

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-storagetype

For some random reason if you use both DBSecurityGroups and storage-type in the stack YAML (which we do in bootstrap-cfn), it results in storage-type being ignored and it will take the default (magnetic) instead.

**Comment by stuartornum** [comment]
Have a manual fix for this using VPC Security groups - need to add to bootstrap-cfn now...

**Comment by ashb** [comment]
Oh the joy of VPC vs classical >_<.

Good spot!
